export const CategoryTypes = {
  SELECTED_CATEGORY_DATA: "SELECTED_CATEGORY_DATA",
  CATEGORY_ITEM_LIST: "CATEGORY_ITEM_LIST",
  REMOVE_CATEGORY_LIST: "REMOVE_CATEGORY_LIST",
  SET_CATEGORY_LIST: "SET_CATEGORY_LIST",
  RESET_CATEGORY: "RESET_CATEGORY",
  ALL_CATEGORY_LIST: "ALL_CATEGORY_LIST",
  ALL_CATEGORY_ITEM_LIST: "ALL_CATEGORY_ITEM_LIST",
  CATEGORY_ITEM_LIST_POS: "CATEGORY_ITEM_LIST_POS",
};
