export const HOMEPAGEMESSAGE = {
  MENU: "Menu",
  MENU_TOOLTIP: "Menu",
  ORDER_ONLINE: "Order Online",
  ORDER_ONLINE_TOOLTIP: "Order Online",
  CLICK_FOR_DELIVERY: "Click For Delivery",
  CLICK_FOR_DELIVERY_TOOLTIP: "Click For Delivery",
  SELECT_LOCATION: "Select Location",
  SELECT_LOCATION_TOOLTIP: "Select Location",
  CLICK_FOR_PICKUP: "Click for pickup",
  CLICK_FOR_PICKUP_TOOLTIP: "Click for pickup",
  CART: "Cart",
  CART_TOOLTIP: "Cart",
  GO_TO_DELIVERY: "Go To Delivery",
  GO_TO_PICKUP: "Go To Pickup",
  ORDER_NOW: "Order Now",
  ORDER_NOW_TOOLTIP: "Order Now",
  APPLY_NOW: "Apply Now",
  APPLY_NOW_TOOLTIP: "Apply Now",
  VIEW_FULL_MENU: "View Full Menu",
  VIEW_FULL_MENU_TOOLTIP: "View Full Menu",
  MY_PROFILE: "My Profile",
  MY_PROFILE_TOOLTIP: "My Profile",
  MY_ORDERS: "My Orders",
  MY_ORDERS_TOOLTIP: "My Orders",
  FAVORITES: "Favorites",
  FAVORITES_TOOLTIP: "Favorites",
  LOGOUT: "Logout",
  LOGOUT_TOOLTIP: "Logout",
  SIGN_IN: "Sign In",
  LOGIN_TOOLTIP: "Login",
  SIGN_IN_MESSAGE: "Login",
  EARN_REAWARDS: "earn rewards",
  // pickup-delivery_popup-message
  CARRYOUT_MESSAGE:
    "Are you looking for your local Delivery or Carryout store?",
  DELIVERY: "Delivery",
  DELIVERY_TOOLTIP: "Delivery",
  PICKUP: "PICKUP",
  PICKUP_TOOLTIP: "PICKUP",
  OR: "Or",
  //PickupDeliverySection popup component
  START_YOUR_ORDER: "Start Your Order",
  ADD_MORE_ITEMS: "Add More Items",
  // SigninLoginPopup component
  SIGN_TO_PROFILE: "SIGN IN TO YOUR PROFILE",
  CREATE_ONE: "CREATE ONE",
  PHONE: "Phone",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password?",
  SECURLY_MESSAGE:
    "Securely access your recent orders, saved locations, and payment methods.",
  // RegisterComponent
  REGISTER: "REGISTER",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  EMAIL: "Email",
  PHONE_NUMBER: "Phone Number",
  CONFIRM_PASSWORD: "Confirm Password",
  ADD_ADDRESS: "Add Address",
  LOGIN: "Login",
  // AddAddressComponent
  FIND_YOUR_ADDRESS: "Find Your Address",
  ADDRESS_1: "Address 1",
  ADDRESS_2: "Address 2",
  ENT_APT: "Enter Apt. Buzzer...",
  CITY: "City",
  PROVINCE_STATE: "Province/State",
  POSTAL_CODE: "Postal Code",
  SAVE_ADDRESS: "Save Address",
  //ForgotPasswordComponent
  RESET_PASSWORD: "Reset Password",
  RESET_PASSWORD_MESSAGE:
    "To reset your password, please enter your Phone Number below.",
  // Banner1
  NEW: "New",
  MIX: "Mix",
  MATCH: "Match",
  EACH: "each",
  // Banner5
  HIRING_TITLE: "We Are Hiring",
  DELIVERY_DRIVER: "Delivery drivers, Pizza Makers and more....",
  //Footer
  EMAIL_OFFER: "Email Offers",
  GIFT_CARDS: "Gift Cards",
  CATERING: "Catering",
  JOIN_OUR_TEAM: "Join Our Team",
  PRIVACY: "Privacy",
  TEARM_OF_USE: "Terms of Use",
  ABOUT_US: "About Us",
  CONTACT_US: "Contact Us + FAQ",
  NUTRITIAL: "Nutritional Guide",
  FOOTER_MESSAGE:
    "An additional charge may apply for premium toppings, sauces, extra cheese, and special pizza types including: Handmade Pan Pizzas, Thin Crust Pizzas, Gluten Free Pizzas and Feast Pizzas.",
  BY_FOOD_CORE: "Powered By FoodCore",
  GO_TO_CART: "Go To Cart",
  OPEN_TABLE: "Reserve Table",
};
