export const ORDERDETAILPAGEMESSAGE = {
  ORDER_DETAILES: "Order Details",
  ORDER_PLACE_MESSAGE: "Item added succesfully",
  ORDER_NO: "Order No",
  Note: "Note",
  DeliveryNote: "Delivery Note",
  TYPE: "Type",
  STATUS: "Status",
  RE_ORDER: "Re-Order",
  REASON: "Reason",
  QTY: "Qty",
  UNIT_PRICE: "Price",
  REWARD_POINTS: "Reward Points",
  DELIVERY: "Delivery",
  // ChargesComponent
  SUB_TOTAL: "Sub Total",
  DISCOUNT: "Discount",
  REEDEM_POINTS: "Reward Points",
  TOTAL_PRE_TAX: "Total Pre-Tax",
  HST_TAX: "HST Tax",
  SYSTEM_ACCESS_FEE: "System Access Fee",
  ORDER_TOTAL: "Order Total",
  TIP: "Tip",
  TRACKING_URL: "Tracking Url",
};
