export const PAGES = {
  REST_CLOSE: "restaurantclose",
  DELIVERY: "delivery",
  MENU: "menu",
  MAIN: "main",
  MYACCOUNT: "myaccount",
  CHECKOUT: "checkout",
  MYORDERS: "myorders",
  FAVOURITE: "favourite",
  TESTIMONIALS: "testimonial",
  LOCATIONS: "locations",
  ABOUTUS: "aboutus",
  TERMS: "terms",
  PRIVACY: "privacy",
  CART: "cart",
  PASS_SET: "password-set",
  RESET_FAIL: "reset-failed",
  PAYMENT: "payment",
  ORDER_CONFIRM: "orderconfirmation",
  THANK_YOU: "thankyou",
  ORDER_DETAIL: "orderdetail",
  CREATE_NEW_PASS: "create-new-password",
  OPENTABLE: "opentable",
};
