export const TableOrderTypes = {
    DISPLAY_HOW_ORDER: "DISPLAY_HOW_ORDER",
    ADD_TABLE_NUMBER: "ADD_TABLE_NUMBER",
    ADD_OTHER_CUSTOMER: "ADD_OTHER_CUSTOMER",
    GET_CART_DATA: "GET_CART_DATA",
    FIREBASE_TABLE_NAME: "FIREBASE_TABLE_NAME",
    GET_CART_TOTAL: "GET_CART_TOTAL",
    GET_TABLE_DETAILS: "GET_TABLE_DETAILS",
    ADD_PRINTER_DETAILS: "ADD_PRINTER_DETAILS",
    GET_CART_COUNT: "GET_CART_COUNT",
    ADD_KITCHEN_COMMENT: "ADD_KITCHEN_COMMENT",
    ADD_SERVER_ID: "ADD_SERVER_ID",
    CLEAR_REDUX: "CLEAR_REDUX"

} as const;