export interface Result {
  locationId: number;
  restaurantId: number;
  locationName: string;
  address1: string;
  cityname: string;
  statename: string;
  phone: string;
  zipcode: string;
  email: string;
  description: string;
  latitude: string;
  longitude: string;
  delivery: boolean;
  isdine: boolean;
  bookingtimelimit: number;
  ordersubmittime: number;
  takeawayextratime: number;
  islocationactive: boolean;
  mindeliverycharge: number;
  maxdeliverymiles: number;
  isOrderingDisable: boolean;
  orderingMessage: string;
  isdelivery: boolean;
  istakeaway: boolean;
  locationURL: string;
  minimumdeliveryorder: number;
  minimumtakeoutorder: number;
  email2?: string;
  IsPayByCard: boolean;
  IsPayByCash: boolean;
  IsTableReservation: boolean;
  SystemAccessFee: number;
  countryName: string;
  currencysymbol: string;
  countrycode: string;
  regioncode: string;
  isGeoFencing: boolean;
  isDeliveryOrderingDisable: boolean;
  isTakeoutOrderingDisable: boolean;
  opentableurl?: null | any;
  opentableactive: boolean;
  isDeliveryAsap: boolean;
  isDeliveryPickupTime: boolean;
  isTakeOutAsap: boolean;
  isTakeOutPickupTime: boolean;
  enableTip: boolean;
  enableRewardPoint: boolean;
  googlePayEnable: boolean;
  applePayEnable: boolean;
  stripePublishKey: string;
  isDisplaySummaryAto: boolean;
  isStripePaymentLive: boolean;
  defaultmenucategoryimage: string;
  defaultmenuitemimage: string;
  defaultsuboptionimage?: null | any;
  enableTimeSlot: boolean;
  timeSlotDuration: number;
  deliveryService: number;
  isUseFudmeDriver: boolean;
  tipYourDriver: string;
  minTipPercentage: number;
  minTipTextMessage?: null | any;
  facebookUrl: string;
  instagramUrl: string;
  displaylistview: boolean;
  enablefutureordering: boolean;
  noofdaysfutureordering: number;
  enabletimeslot: boolean;
  timeduration: number;
  defaultordertype: boolean;
  b2btype: boolean;
  futureOrderingDayDates: any[];
}

export interface Root {
  d: {
    result: Result;
    message: string;
    status: number;
  };
}

export type DefaultLocation = {
  IsPayByCard: boolean;
  IsPayByCash: boolean;
  IsTableReservation: boolean;
  SystemAccessFee: number;
  address1: string;
  applePayEnable: boolean;
  b2btype: boolean;
  bookingtimelimit: number;
  cityname: string;
  countryName: string;
  countrycode: string;
  currencysymbol: string;
  defaultmenucategoryimage: string;
  defaultmenuitemimage: string;
  defaultordertype: boolean;
  defaultsuboptionimage: string;
  delivery: boolean;
  deliveryService: number;
  description: string;
  displaylistview: boolean;
  email: string;
  email2: string;
  enableRewardPoint: boolean;
  enableTimeSlot: boolean;
  enableTip: boolean;
  enablefutureordering: boolean;
  enabletimeslot: boolean;
  facebookUrl: string;
  futureOrderingDayDates: any[]; // or a specific date type if you know it
  googlePayEnable: boolean;
  instagramUrl: string;
  isDeliveryAsap: boolean;
  isDeliveryOrderingDisable: boolean;
  isDeliveryPickupTime: boolean;
  isDisplaySummaryAto: boolean;
  isGeoFencing: boolean;
  isOrderingDisable: boolean;
  isStripePaymentLive: boolean;
  isTakeOutAsap: boolean;
  isTakeOutPickupTime: boolean;
  isTakeoutOrderingDisable: boolean;
  isUseFudmeDriver: boolean;
  isdelivery: boolean;
  isdine: boolean;
  islocationactive: boolean;
  istakeaway: boolean;
  latitude: string;
  locationId: number;
  locationName: string;
  locationURL: string;
  longitude: string;
  maxdeliverymiles: number;
  minTipPercentage: number;
  minTipTextMessage: string;
  mindeliverycharge: number;
  minimumdeliveryorder: number;
  minimumtakeoutorder: number;
  noofdaysfutureordering: number;
  opentableactive: boolean;
  opentableurl: string;
  orderingMessage: string;
  ordersubmittime: number;
  phone: string;
  regioncode: string;
  restaurantId: number;
  statename: string;
  stripePublishKey: string;
  takeawayextratime: number;
  timeSlotDuration: number;
  timeduration: number;
  tipYourDriver: string;
  zipcode: string;
};

export type RestaurantDetail = {
  IsAddressMandatoryForRegister: boolean;
  IsBlobStorage: boolean;
  androidlink: string;
  bannercount: number;
  color: string;
  defaultlocationId: number;
  deliveryServicePartnerEnable: boolean;
  displayLocationPopUpChange: boolean;
  enableotpauthentication: boolean;
  facebooklink: string;
  firebaseConfig: any; // Replace `any` with a more specific type if known
  googleplacekey: string;
  instagram: string;
  ioslink: string;
  isSchoolProgramEnabled: boolean;
  isTakeOut: boolean;
  isdelivery: boolean;
  issupplychainenable: boolean;
  istakeaway: boolean;
  iswaiting: boolean;
  linkedin: string;
  locationId: number;
  locationIds: number[];
  locationName: string | null;
  logo: string;
  profilename: string;
  restaurantColorModel: any[]; // Replace `any` if you have the structure
  restaurantId: number;
  restaurantURL: string;
  restaurantWindowTime: any; // Replace with `Date | null` if time-based
  restaurantappicon: string;
  restaurantname: string;
  skype: string;
  smsapigateway: number;
  themetype: number;
  twiterlink: string;
  website: string;
};
