// Load environment variable
export const BASE_URL: string = process.env.NEXT_PUBLIC_WEB_API_URL || "";

const proxy: string = "";

export const ENDPOINTS : Record<string, string> = {
  PROXY: `${proxy}`,
  BASE_URL: `${BASE_URL}`,
  GET_RESTAURANTS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllRestaurantInfo`,
  GET_MENU_CATEGORY: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getMenuCategory_Version2`,
  //GET_ALL_MENU_ITEMS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllMenuItems`,
  GET_CATEGORY_MENUITEM_LIST: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCategoryMenuitemList`,
  // GET_MENU_ITEMS_DETAILS: `${BASE_URL}/RestaurantAPIOnlineV2.asmx/getMenuItemDetail`,
  GET_MENU_ITEMS_DETAILS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getMenuItemDetail`,
  ADD_FAVORITE: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/addFavorite`,
  DELETE_FAVORITE: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/DeleteFavorite`,
  ADD_ITEM_TO_CART: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/addToCart`,
  GET_CART_ITEM: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCartItems`,
  GET_ALL_FAVORITES: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getMenuItemFavorite_Version1`,
  LOGIN: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/loginVerification`,
  REGISTER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/registerUser`,
  GET_LOCATIONS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllLocationInfoWeb`,
  GET_ALLLOCATION: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllLocationInfoNew`,
  GET_CART_ITEM_COUNT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCartItemsCount`,
  DELETE_CART_ITEM: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/removeCartItem`,
  GET_LOCATION_TIMMING: `${BASE_URL}/RestaurantAPIOnlineV2.asmx/GetRestaurantDeliveryTakeOutTime`,
  GET_TODAY_RESTAURANTHOURS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getTodayOpenCloseTime`,
  CHECK_CUSTOMER_REWARD_POINTS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/checkCustomerRewardPoints`,
  UPDATE_QUANTITY: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/updateCartItem`,
  GET_CART_TOTAL: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCartItemsTotal`,
  GET_ORDER_HISTORY: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getOrderHistoryV1`,
  CHECK_ORDER_TIME: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/checkTime`,
  GET_DELIVERY_CHARGES: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getDeliveryChargesInfo`,
  CART_CHECKOUT: `${BASE_URL}/`,
  GET_TESTIMONIALS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getTestimonialOfRestaurant`,
  ADD_TESTIMONIALS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/addTestimonial`,
  GET_ALL_LOCATION_List: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllLocationList`,
  GET_ALL_NOTIFICATION_List: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getNotification`,
  GET_ORDER_INFO: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getOrderDetailsInfo`,
  REPEAT_ORDER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/repeatOrder`,
  GET_PAYMENT_INTENT_ID: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getPaymentIntent`,
  CONFIRM_STRIPE_PAYMENT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/confirmCardPayment`,
  GET_DELIVERY_ADDRESS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getDeliveryAddress_Version1`,
  // ADD_DELIVERY_ADDRESS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/addDeliveryAddresss_V1`,
  ADD_DELIVERY_ADDRESS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/addDeliveryAddresss`,

  DELETE_DELIVERY_ADDRESS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/deleteDeliveryAddress`,
  GET_CUSTOMER_PASSWORD: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCustomerPassword`,
  UPDATE_CUSTOMER: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/addUpdateCustomerV3`,
  GET_CUSTOMER_INFO: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getCustomerDetails`,
  GET_CUSTOMER_INFO_V1: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getCustomerDetailsV1`,
  CHECKOUT_ORDER: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getCustomerDetails`,
  PLACE_ORDER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/addOrdersWeb`,
  COUNTRY_LIST: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllCountryList`,
  GET_ORDER_TIME: `${BASE_URL}/RestaurantAPIOnlineV2.asmx/GetOrderTime`,
  GET_SELECTED_RESTAURANT_TIME: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getSelectedRestaurantTime`,
  ADD_ORDER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/addOrder`,
  USER_EXIST: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/userExists`,
  FORGOT_PASSWORD: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/forgotPassword`,
  RESET_PASSWORD_VALIDTOKEN: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/resetPasswordValidTokenRequest`,
  RESET_PASSWORD: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/resetpasswordRequest`,
  LOCATION_BY_ID: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getLocationInfoById`,
  OTP_VERIFICATION_SETTING: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getOTPVerificationSetting`,
  TWILIO_SEND_CODE: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/twilioSendCode`,
  TWILIO_VERIFY_CODE: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/twilioVerifyCode`,
  GET_RESTAURANT_LOCATIONS_LIST: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllRestaurantAndLocationDetail`,
  DELETE_CART_FROM_SESSIONID: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/removeCartItemFromSessionId`,
  GET_TIMING: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getTiming`,
  UPDATE_CART_ORDER_ITEMS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/UpdateCartOrders`,
  UPDATE_CONFIRM_PAYMENT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/updateAndConfirmPaymentIntent`,
  GET_HOMEPAGE_BANNER_LIST: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getHomepageBanners`,
  VERIFY_DELIVERY_ADDRESS_MAX_LIMIT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/verifyDeliveryAddresss`,
  GOOGLE_MAP_LINK: "https://maps.google.com/?q=",
  ERROR_LOG: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/errorLogWeb`,
  REGISTER_USER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/registerWithoutAddress`,
  GET_SEARCH_RESULT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getMenuItemSerch`,
  GET_CATEGORIES_RELATIVE_ITEMS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getCategoriesRelativeItems`,
  QUICK_ORDER_ADD_TO_CART: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/QuickOrderaddToCart`,
  AFTER_PAYMENT_SUCCESS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/afterPaymentSuccess`,
  GET_THEME_TYPE: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getThemeTypeAndSEODetails`,
  // GET_THEME_TYPE: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getThemeType`,
  VERIFY_EMAIL: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/verifyEmail`,
  SEND_VERIFICATION_EMAIL: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/sendVerificationEmail`,
  GET_PAGE_CONTENT_RESTAURANT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getPageContentRestaurant`,
  GET_METADATA_DETAILS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getSEODetails`,
  UPDATE_VERIFIED_PHONE: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/updateVerifiedPhoneNumber`,
  CHECK_EXIST_CUSTOMER_PHONE_NUMBER: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/checkExistingCustomerPhoneNumber`,
  GET_CURRENT_TIME: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getCurrentTime`,
  GET_DELIVERY_DETAILS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/GetDeliveryServiceOrderDetails`,
  GET_PAYMENT_DETAILS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getPaymentDetails`,
  ORDER_DETAIL_INFO_GUID: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getOrderDetailsInfoByGUID`,
  GET_MENU_CATEGORY_POS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getMenuCategory_Version1POS`,
  GET_CATEGORY_ITEMS_POS: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getAllMenuItems_Version2POS`,
  GET_CUSTOMER_BY_PHONE: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getCustomerByPhone`,
  INSERT_TO_OTHER_CUSTOMER: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/insertothercustomer`,
  GET_POS_TABLE_DETAILS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getPosTableDetails`,
  GET_PRINTER_INFORMATION: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getListofPrinterSetting`,
  GET_POS_MENUITEM_SEARCH: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getPOSMenuItemSearch`,
  SEND_TABLE_PUSH_NOTIFICATION: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/sendTablePushnotification`,
  GET_SYSTEM_CUSTOMER: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/getSystemCustomer`,
  GENERATE_TIMESLOT: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/GenerateTimeSlots`,
  CHECKTIMEBYSLOT: `${BASE_URL}/RestaurantAPIOnlineWebV2.asmx/checkTimeBySlot`,
  ADD_ORDERS_TABLE: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/addOrders`,
  GET_ALL_CATEGORY_MENU_ITEMS: `${BASE_URL}/RestaurantAPIOnlineWebV1.asmx/getAllMenuCategoryItems`,
  CHECK_CUSTOMER_REWARD_POINT_LOCATION: `${BASE_URL}/RestaurantAPIOnlineV1.asmx/checkCustomerRewardPointsV1`,
};
